/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package td4;

import org.junit.jupiter.api.Test;
import td4.exo1.App;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
}
