/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package td4.exo1;

import td4.IncorrectStateException;

public class App
{

    //test du prof
    public static void main(String[] args) {
        SimpleVendingMachineContext machine = new SimpleVendingMachineContext();
        //
        try {
            machine.askCoffee();
        }
        catch (IncorrectStateException e) {
            System.out.println(e);}
        //
        try {
            machine.give(5); // { 5 }
            machine.askCoffee();
        }
        catch (IncorrectStateException e) {
            System.out.println(e);
        }
        //
        try {
            machine.give(30); // { 35 }
            machine.askCoffee(); // { 30 }
        }
        catch (IncorrectStateException e) {
            System.out.println(e);
        }
        //
        try {
            machine.give(1); // { 1 }
            machine.askCoffee(); // { 1 }
        }
        catch (IncorrectStateException e) {
            System.out.println(e);
        }
    }
}
